<div class="locked" style="width: 1199px; height: 328px; position: fixed; left: 0px; top: 0px; z-index: -1; visibility: visible;">
                <div style="position: absolute; overflow: hidden; width: 100%; height: 100%;"><div class="video-inner" data-width="1440" data-height="810" style="position: absolute; left: 50%; top: 50%; width: 1199px; height: 674.4375px; margin-left: -599.5px; margin-top: -337.21875px;">
                    
                <video loop="loop" preload="auto" data-fallback="http://pitchfork-features-cdn.s3.amazonaws.com/features/cover-story/reader/savages/video/Savages-2022-v1-5000_mpeg4.webm.gif" data-mp4-src="http://pitchfork-features-cdn.s3.amazonaws.com/features/cover-story/reader/savages/video/Savages-2022-v1-5000_mpeg4.mp4" data-ogv-src="http://pitchfork-features-cdn.s3.amazonaws.com/features/cover-story/reader/savages/video/Savages-2022-v1-5000_mpeg4.ogv" data-webm-src="http://pitchfork-features-cdn.s3.amazonaws.com/features/cover-story/reader/savages/video/Savages-2022-v1-5000_mpeg4.webm"><source src="http://pitchfork-features-cdn.s3.amazonaws.com/features/cover-story/reader/savages/video/Savages-2022-v1-5000_mpeg4.mp4" type="video/mp4"><source src="http://pitchfork-features-cdn.s3.amazonaws.com/features/cover-story/reader/savages/video/Savages-2022-v1-5000_mpeg4.ogv" type="video/ogg"><source src="http://pitchfork-features-cdn.s3.amazonaws.com/features/cover-story/reader/savages/video/Savages-2022-v1-5000_mpeg4.webm" type="video/webm"></video></div></div>
            </div>


<div style="position: absolute; overflow: hidden; width: 100%; height: 100%;"><div class="video-inner" data-width="1440" data-height="810" style="position: absolute; left: 50%; top: 50%; width: 1199px; height: 674.4375px; margin-left: -599.5px; margin-top: -337.21875px;">
                    
                <video loop="loop" preload="auto" data-fallback="http://pitchfork-features-cdn.s3.amazonaws.com/features/cover-story/reader/savages/video/Savages-2022-v1-5000_mpeg4.webm.gif" data-mp4-src="http://pitchfork-features-cdn.s3.amazonaws.com/features/cover-story/reader/savages/video/Savages-2022-v1-5000_mpeg4.mp4" data-ogv-src="http://pitchfork-features-cdn.s3.amazonaws.com/features/cover-story/reader/savages/video/Savages-2022-v1-5000_mpeg4.ogv" data-webm-src="http://pitchfork-features-cdn.s3.amazonaws.com/features/cover-story/reader/savages/video/Savages-2022-v1-5000_mpeg4.webm"><source src="http://pitchfork-features-cdn.s3.amazonaws.com/features/cover-story/reader/savages/video/Savages-2022-v1-5000_mpeg4.mp4" type="video/mp4"><source src="http://pitchfork-features-cdn.s3.amazonaws.com/features/cover-story/reader/savages/video/Savages-2022-v1-5000_mpeg4.ogv" type="video/ogg"><source src="http://pitchfork-features-cdn.s3.amazonaws.com/features/cover-story/reader/savages/video/Savages-2022-v1-5000_mpeg4.webm" type="video/webm"></video></div></div>

<div class="video-inner" data-width="1440" data-height="810" style="position: absolute; left: 50%; top: 50%; width: 1199px; height: 674.4375px; margin-left: -599.5px; margin-top: -337.21875px;">
                    
                <video loop="loop" preload="auto" data-fallback="http://pitchfork-features-cdn.s3.amazonaws.com/features/cover-story/reader/savages/video/Savages-2022-v1-5000_mpeg4.webm.gif" data-mp4-src="http://pitchfork-features-cdn.s3.amazonaws.com/features/cover-story/reader/savages/video/Savages-2022-v1-5000_mpeg4.mp4" data-ogv-src="http://pitchfork-features-cdn.s3.amazonaws.com/features/cover-story/reader/savages/video/Savages-2022-v1-5000_mpeg4.ogv" data-webm-src="http://pitchfork-features-cdn.s3.amazonaws.com/features/cover-story/reader/savages/video/Savages-2022-v1-5000_mpeg4.webm"><source src="http://pitchfork-features-cdn.s3.amazonaws.com/features/cover-story/reader/savages/video/Savages-2022-v1-5000_mpeg4.mp4" type="video/mp4"><source src="http://pitchfork-features-cdn.s3.amazonaws.com/features/cover-story/reader/savages/video/Savages-2022-v1-5000_mpeg4.ogv" type="video/ogg"><source src="http://pitchfork-features-cdn.s3.amazonaws.com/features/cover-story/reader/savages/video/Savages-2022-v1-5000_mpeg4.webm" type="video/webm"></video></div>


<video loop="loop" preload="auto" data-fallback="http://pitchfork-features-cdn.s3.amazonaws.com/features/cover-story/reader/savages/video/Savages-2022-v1-5000_mpeg4.webm.gif" data-mp4-src="http://pitchfork-features-cdn.s3.amazonaws.com/features/cover-story/reader/savages/video/Savages-2022-v1-5000_mpeg4.mp4" data-ogv-src="http://pitchfork-features-cdn.s3.amazonaws.com/features/cover-story/reader/savages/video/Savages-2022-v1-5000_mpeg4.ogv" data-webm-src="http://pitchfork-features-cdn.s3.amazonaws.com/features/cover-story/reader/savages/video/Savages-2022-v1-5000_mpeg4.webm"><source src="http://pitchfork-features-cdn.s3.amazonaws.com/features/cover-story/reader/savages/video/Savages-2022-v1-5000_mpeg4.mp4" type="video/mp4"><source src="http://pitchfork-features-cdn.s3.amazonaws.com/features/cover-story/reader/savages/video/Savages-2022-v1-5000_mpeg4.ogv" type="video/ogg"><source src="http://pitchfork-features-cdn.s3.amazonaws.com/features/cover-story/reader/savages/video/Savages-2022-v1-5000_mpeg4.webm" type="video/webm"></video>
<source src="http://pitchfork-features-cdn.s3.amazonaws.com/features/cover-story/reader/savages/video/Savages-2022-v1-5000_mpeg4.mp4" type="video/mp4">
<source src="http://pitchfork-features-cdn.s3.amazonaws.com/features/cover-story/reader/savages/video/Savages-2022-v1-5000_mpeg4.ogv" type="video/ogg">
<source src="http://pitchfork-features-cdn.s3.amazonaws.com/features/cover-story/reader/savages/video/Savages-2022-v1-5000_mpeg4.webm" type="video/webm">
